DROP TABLE IF EXISTS m_product;
CREATE TABLE m_product(
	m_product_id CHARACTER VARYING(32) NOT NULL,
	ad_org_id CHARACTER VARYING(32) NOT NULL,
	ad_client_id CHARACTER VARYING(32) NOT NULL,	
	isactive CHARACTER VARYING(1) CHECK(isactive IN('Y','N')),
	created TIMESTAMP NOT NULL DEFAULT NOW(),
	createdby CHARACTER VARYING(32) NOT NULL,
	updated TIMESTAMP NOT NULL DEFAULT NOW(),
	updatedby CHARACTER VARYING(32) NOT NULL,
	value CHARACTER VARYING(50) NOT NULL,
	name CHARACTER VARYING(100) NOT NULL,	
	CONSTRAINT m_product_key PRIMARY KEY(m_product_id)
)

